/**
 * EIGHTEEN — The Celestial Deities of Chandrakhani Pass
 *
 * Real astronomical catalogue of 18 deep-sky objects visible from
 * Rumsu & Naggar (32.1198° N, 77.1731° E) at 2,180m altitude.
 *
 * Sourced from Messier & NGC Astronomical Catalogues with exact coordinates.
 * Each object corresponds to one of the 18 deities scattered from Jamlu Rishi's
 * basket over the Himalayan crest.
 */

export interface CelestialGod {
  id: number
  slug: string
  name: string
  deity: string
  deityRole: string
  designation: string
  constellation: string
  ra: string           // Right Ascension
  dec: string          // Declination
  magnitude: number
  distanceLightYears: string
  riseTimeLocal: string
  observationNote: string
  lore: string
}

export const EIGHTEEN_GODS: readonly CelestialGod[] = [
  {
    id: 1,
    slug: 'm31-andromeda',
    name: 'The Great Spiral',
    deity: 'Jamlu Rishi',
    deityRole: 'Keeper of Malana & Chandrakhani Pass',
    designation: 'Messier 31 (NGC 224)',
    constellation: 'Andromeda',
    ra: '00h 42m 44s',
    dec: '+41° 16′ 09″',
    magnitude: 3.44,
    distanceLightYears: '2,500,000 ly',
    riseTimeLocal: '18:15',
    observationNote: 'A naked-eye galactic spindle across the crest of the Pir Panjal.',
    lore: 'The patriarch rishi whose basket held the eighteen seeds of celestial order before the great storm.',
  },
  {
    id: 2,
    slug: 'm45-pleiades',
    name: 'The Seven Sisters',
    deity: 'Gauri Shankar',
    deityRole: 'Lord of the Valley Convergence',
    designation: 'Messier 45 (Melotte 22)',
    constellation: 'Taurus',
    ra: '03h 47m 24s',
    dec: '+24° 07′ 00″',
    magnitude: 1.6,
    distanceLightYears: '444 ly',
    riseTimeLocal: '19:40',
    observationNote: 'Cobalt-blue reflection nebulae glittering over the orchard ridge.',
    lore: 'The primordial union carved in stone at Naggar temple, mirrored in azure light above.',
  },
  {
    id: 3,
    slug: 'm42-orion',
    name: 'The Great Nebula',
    deity: 'Bijli Mahadev',
    deityRole: 'Bearer of the Celestial Lightning',
    designation: 'Messier 42 (NGC 1976)',
    constellation: 'Orion',
    ra: '05h 35m 17s',
    dec: '-05° 23′ 28″',
    magnitude: 4.0,
    distanceLightYears: '1,344 ly',
    riseTimeLocal: '21:30',
    observationNote: 'Violet-winged stellar nursery igniting across the southern valley pass.',
    lore: 'The high staff on Mathan peak that attracts the sky’s thunder, shattering and reforming.',
  },
  {
    id: 4,
    slug: 'm13-hercules',
    name: 'The Great Globular Cluster',
    deity: 'Tripura Sundari',
    deityRole: 'Goddess of the Three Realms',
    designation: 'Messier 13 (NGC 6205)',
    constellation: 'Hercules',
    ra: '16h 41m 41s',
    dec: '+36° 27′ 35″',
    magnitude: 5.8,
    distanceLightYears: '22,200 ly',
    riseTimeLocal: '16:10',
    observationNote: 'Hundreds of thousands of ancient stars condensed into a brilliant core.',
    lore: 'The three-tiered pagoda temple of Naggar, radiating balance over forest and stone.',
  },
  {
    id: 5,
    slug: 'm57-ring-nebula',
    name: 'The Ring Nebula',
    deity: 'Basheshwar Mahadev',
    deityRole: 'Guardian of the Beas Confluence',
    designation: 'Messier 57 (NGC 6720)',
    constellation: 'Lyra',
    ra: '18h 53m 35s',
    dec: '+33° 01′ 45″',
    magnitude: 8.8,
    distanceLightYears: '2,570 ly',
    riseTimeLocal: '17:05',
    observationNote: 'A luminous spectral ring suspended high in the zenith at dark.',
    lore: 'The carved stone mandala at Bajaura where the river waters turn north toward the glaciers.',
  },
  {
    id: 6,
    slug: 'm27-dumbbell',
    name: 'The Dumbbell Nebula',
    deity: 'Hadimba Devi',
    deityRole: 'Guardian of the Cedar Forest',
    designation: 'Messier 27 (NGC 6853)',
    constellation: 'Vulpecula',
    ra: '19h 59m 36s',
    dec: '+22° 43′ 16″',
    magnitude: 7.5,
    distanceLightYears: '1,360 ly',
    riseTimeLocal: '17:45',
    observationNote: 'Hourglass expanse of ionized gas framed by giant Himalayan deodars.',
    lore: 'The mother spirit dwelling among unhewn roots and massive ancient timbers.',
  },
  {
    id: 7,
    slug: 'm33-triangulum',
    name: 'The Pinwheel Galaxy',
    deity: 'Vashishta Rishi',
    deityRole: 'Sage of the Hot Springs',
    designation: 'Messier 33 (NGC 598)',
    constellation: 'Triangulum',
    ra: '01h 33m 50s',
    dec: '+30° 39′ 37″',
    magnitude: 5.72,
    distanceLightYears: '2,730,000 ly',
    riseTimeLocal: '19:00',
    observationNote: 'Faint sprawling face-on spiral visible through our 200mm refractor.',
    lore: 'The ascetic who rested beside subterranean thermal waters as glaciers retreated.',
  },
  {
    id: 8,
    slug: 'ngc869-double-cluster',
    name: 'The Perseus Double Cluster',
    deity: 'Shringi Rishi',
    deityRole: 'Bringer of Alpine Rains',
    designation: 'NGC 869 & NGC 884',
    constellation: 'Perseus',
    ra: '02h 20m 00s',
    dec: '+57° 08′ 00″',
    magnitude: 3.7,
    distanceLightYears: '7,500 ly',
    riseTimeLocal: '18:50',
    observationNote: 'Twin diamond swarms blazing near the northern ridgeline.',
    lore: 'The horned sage whose chants summons monsoon clouds from the plains into the high passes.',
  },
  {
    id: 9,
    slug: 'm81-bodes-galaxy',
    name: "Bode's Galaxy",
    deity: 'Adi Brahma',
    deityRole: 'Lord of the Village Khokhan',
    designation: 'Messier 81 (NGC 3031)',
    constellation: 'Ursa Major',
    ra: '09h 55m 33s',
    dec: '+69° 03′ 55″',
    magnitude: 6.94,
    distanceLightYears: '11,800,000 ly',
    riseTimeLocal: '23:45',
    observationNote: 'Symmetric grand design spiral floating beside the Great Bear.',
    lore: 'The four-faced architect of sacred timber craft whose shrine stands in Khokhan.',
  },
  {
    id: 10,
    slug: 'm82-cigar-galaxy',
    name: 'The Cigar Galaxy',
    deity: 'Ganesh Devta',
    deityRole: 'Remover of High Pass Obstacles',
    designation: 'Messier 82 (NGC 3034)',
    constellation: 'Ursa Major',
    ra: '09h 55m 52s',
    dec: '+69° 40′ 47″',
    magnitude: 8.41,
    distanceLightYears: '12,000,000 ly',
    riseTimeLocal: '23:50',
    observationNote: 'Starburst galaxy with intense hydrogen filament ejections.',
    lore: 'First invoked at the threshold before ascending steep cliffs toward Chandrakhani.',
  },
  {
    id: 11,
    slug: 'm15-pegasus',
    name: 'The Pegasus Cluster',
    deity: 'Karthikeya (Swami)',
    deityRole: 'Guardian of the Ridge Line',
    designation: 'Messier 15 (NGC 7078)',
    constellation: 'Pegasus',
    ra: '21h 29m 58s',
    dec: '+12° 10′ 01″',
    magnitude: 6.2,
    distanceLightYears: '33,600 ly',
    riseTimeLocal: '18:20',
    observationNote: 'Dense core collapse globular containing an elusive central black hole.',
    lore: 'The warrior deity protecting the high alpine pasture boundaries against winter frost.',
  },
  {
    id: 12,
    slug: 'm2-aquarius',
    name: 'The Aquarius Cluster',
    deity: 'Manu Maharaj',
    deityRole: 'Progenitor of Manali',
    designation: 'Messier 2 (NGC 7089)',
    constellation: 'Aquarius',
    ra: '21h 33m 27s',
    dec: '-00° 49′ 24″',
    magnitude: 6.3,
    distanceLightYears: '37,000 ly',
    riseTimeLocal: '18:35',
    observationNote: 'Luminous spherical cluster with over 150,000 stars.',
    lore: 'Whose vessel landed on the crest of Manali after the great deluge waters receded.',
  },
  {
    id: 13,
    slug: 'albireo-cygnus',
    name: 'The Double Star of Cygnus',
    deity: 'Narayana Devta',
    deityRole: 'Keeper of Jagatsukh',
    designation: 'Beta Cygni (Albireo)',
    constellation: 'Cygnus',
    ra: '19h 30m 43s',
    dec: '+27° 57′ 35″',
    magnitude: 3.05,
    distanceLightYears: '430 ly',
    riseTimeLocal: '16:40',
    observationNote: 'The most breathtaking topaz-gold and sapphire-blue contrast pair in the heavens.',
    lore: 'The eternal balance of sun and snow residing in the ancient capital of Jagatsukh.',
  },
  {
    id: 14,
    slug: 'ngc7000-north-america',
    name: 'North America Nebula',
    deity: 'Dhumal Devta',
    deityRole: 'Spirit of Smoke and Fire',
    designation: 'NGC 7000 (Caldwell 20)',
    constellation: 'Cygnus',
    ra: '20h 58m 47s',
    dec: '+44° 19′ 48″',
    magnitude: 4.0,
    distanceLightYears: '2,202 ly',
    riseTimeLocal: '17:15',
    observationNote: 'Rich interstellar ionized hydrogen clouds glowing faint crimson.',
    lore: 'The hearth smoke rising from kitchen chulhas, joining mist above the forest roof.',
  },
  {
    id: 15,
    slug: 'm92-hercules',
    name: 'The Outer Hercules Cluster',
    deity: 'Ghepan Devta',
    deityRole: 'Lord of the High Lahaul Passes',
    designation: 'Messier 92 (NGC 6341)',
    constellation: 'Hercules',
    ra: '17h 17m 07s',
    dec: '+43° 08′ 11″',
    magnitude: 6.3,
    distanceLightYears: '26,700 ly',
    riseTimeLocal: '15:55',
    observationNote: 'One of the oldest star clusters known, dating to over 13 billion years.',
    lore: 'The fierce guardian beyond the Rohtang crest, standing vigil over frozen plateaus.',
  },
  {
    id: 16,
    slug: 'm39-open-cluster',
    name: 'The Cygnus Cloud',
    deity: 'Chamunda Devi',
    deityRole: 'Defender of the Valley Gates',
    designation: 'Messier 39 (NGC 7092)',
    constellation: 'Cygnus',
    ra: '21h 32m 12s',
    dec: '+48° 26′ 00″',
    magnitude: 4.6,
    distanceLightYears: '1,010 ly',
    riseTimeLocal: '17:20',
    observationNote: 'Triangular open cluster sparkling within the dense Milky Way plane.',
    lore: 'The fierce protectress watchful over entry into the sanctum of the valley.',
  },
  {
    id: 17,
    slug: 'm52-cassiopeia',
    name: "The Scorpion's Salt",
    deity: 'Bhirgu Rishi',
    deityRole: 'Sage of Bhrigu Lake',
    designation: 'Messier 52 (NGC 7654)',
    constellation: 'Cassiopeia',
    ra: '23h 24m 12s',
    dec: '+61° 35′ 00″',
    magnitude: 5.0,
    distanceLightYears: '5,000 ly',
    riseTimeLocal: '18:10',
    observationNote: 'Rich starfield containing nearly 200 luminous young stars.',
    lore: 'Whose high alpine tarn remains turquoise and crystalline even through midsummer.',
  },
  {
    id: 18,
    slug: 'm103-cassiopeia',
    name: 'The Northern Fan',
    deity: 'Kailash Mahadev',
    deityRole: 'Lord of the Eternal Summit',
    designation: 'Messier 103 (NGC 581)',
    constellation: 'Cassiopeia',
    ra: '01h 33m 24s',
    dec: '+60° 39′ 00″',
    magnitude: 7.4,
    distanceLightYears: '10,000 ly',
    riseTimeLocal: '18:40',
    observationNote: 'A delicate wedge of ruby and amber stars pointing toward the pole star.',
    lore: 'The eternal throne of silence crowning the Himalayan mountain chain.',
  },
]
