export const blogPosts = [
  {
    id: 1,
    slug: 'best-time-visit-manali-naggar',
    title: 'Best Time to Visit Manali & Naggar: A Seasonal Guide',
    category: 'Travel Guide',
    date: 'May 2026',
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&q=80&w=600',
    excerpt: 'Discover the perfect time to visit the Himalayas. We break down each season in Naggar, from spring flowers to winter snowfall, to help you plan your mountain escape.',
    readTime: 5,
    content: 'Detailed guide about seasons in Naggar...',
  },
  {
    id: 2,
    slug: 'himalayan-homestay-experience',
    title: 'The Himalayan Homestay Experience: Beyond Hotels',
    category: 'Lifestyle',
    date: 'April 2026',
    image: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&q=80&w=600',
    excerpt: 'Why staying in a curated mountain home transforms your travel. We explore the art of hospitality and the magic of waking up to Himalayan peaks.',
    readTime: 7,
    content: 'Detailed article about homestay experience...',
  },
  {
    id: 3,
    slug: 'mountain-photography-tips-himalayas',
    title: 'Mountain Photography Tips: Capturing Himalayan Sunrises',
    category: 'Photography',
    date: 'March 2026',
    image: 'https://images.unsplash.com/photo-1519974719765-e6559eac2575?auto=format&fit=crop&q=80&w=600',
    excerpt: 'From golden hour light to mist valleys, learn how to capture the soul of the Himalayas. Photography tips from House of Hulda guests.',
    readTime: 6,
    content: 'Detailed photography guide...',
  },
  {
    id: 4,
    slug: 'trekking-trails-near-manali',
    title: 'Hidden Trekking Trails Near Manali: Local Secrets',
    category: 'Adventure',
    date: 'February 2026',
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&q=80&w=600',
    excerpt: 'Explore lesser-known trails around Manali and Naggar. Discover serene forests, alpine meadows, and breathtaking vistas away from crowded tourist routes.',
    readTime: 8,
    content: 'Detailed trekking guide...',
  },
  {
    id: 5,
    slug: 'local-cuisine-manali-culinary-journey',
    title: 'Local Cuisine of Manali: A Culinary Journey',
    category: 'Food',
    date: 'January 2026',
    image: 'https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&q=80&w=600',
    excerpt: 'Taste authentic Himachali food. Discover traditional recipes, local flavors, and the stories behind mountain cuisine.',
    readTime: 5,
    content: 'Detailed food guide...',
  },
  {
    id: 6,
    slug: 'wellness-retreat-mountain-living',
    title: 'Wellness Retreat Guide: Mountain Living for Mental Peace',
    category: 'Wellness',
    date: 'December 2025',
    image: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&q=80&w=600',
    excerpt: 'Escape the chaos and find inner peace in the mountains. Yoga, meditation, and the healing power of altitude and fresh mountain air.',
    readTime: 7,
    content: 'Detailed wellness guide...',
  },
];
