export const products = [
  // Pantry
  {
    id: 'himalayan-honey',
    name: 'Wild Himalayan Honey',
    category: 'Pantry',
    price: 450,
    weight: '250g',
    description: 'Raw, unfiltered honey harvested from wild Himalayan beehives above 2,000m. Rich in mountain wildflower pollen.',
    image: 'https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?auto=format&fit=crop&q=80&w=600',
    featured: true,
  },
  {
    id: 'dried-apricots',
    name: 'Kullu Dried Apricots',
    category: 'Pantry',
    price: 320,
    weight: '200g',
    description: 'Sun-dried apricots from the Kullu valley orchards. Naturally sweet with no added sugar or preservatives.',
    image: 'https://images.unsplash.com/photo-1546069901-d5bfd2cbfb1f?auto=format&fit=crop&q=80&w=600',
    featured: false,
  },
  {
    id: 'walnuts',
    name: 'Kinnaur Walnuts',
    category: 'Pantry',
    price: 380,
    weight: '250g',
    description: 'Hand-picked premium walnuts from the high-altitude orchards of Kinnaur. Rich and buttery in flavour.',
    image: 'https://images.unsplash.com/photo-1599599810769-bcde5a160d32?auto=format&fit=crop&q=80&w=600',
    featured: false,
  },
  {
    id: 'saffron',
    name: 'Kashmiri Saffron',
    category: 'Pantry',
    price: 650,
    weight: '1g',
    description: 'Authentic Kashmiri saffron threads — deep crimson with an intense floral aroma. A true Himalayan treasure.',
    image: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&q=80&w=600',
    featured: true,
  },

  // Textiles
  {
    id: 'kullu-shawl',
    name: 'Kullu Woolen Shawl',
    category: 'Textiles',
    price: 1800,
    weight: null,
    description: 'Hand-loomed shawl from Kullu in traditional geometric patterns. Pure wool, warm enough for Himalayan winters.',
    image: 'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?auto=format&fit=crop&q=80&w=600',
    featured: true,
  },
  {
    id: 'woolen-socks',
    name: 'Mountain Wool Socks',
    category: 'Textiles',
    price: 380,
    weight: null,
    description: 'Thick hand-knit socks in natural undyed Himalayan wool. Essential for mountain mornings.',
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&q=80&w=600',
    featured: false,
  },
  {
    id: 'muffler',
    name: 'Hand-Knit Muffler',
    category: 'Textiles',
    price: 550,
    weight: null,
    description: 'Artisan-knit muffler in soft merino wool. Available in forest greens and earth tones.',
    image: 'https://images.unsplash.com/photo-1608228088998-57828365d486?auto=format&fit=crop&q=80&w=600',
    featured: false,
  },

  // Crafts
  {
    id: 'wooden-box',
    name: 'Deodar Wood Carved Box',
    category: 'Crafts',
    price: 1200,
    weight: null,
    description: 'Hand-carved jewellery box from fragrant deodar cedar. Each piece unique, made by artisans in Naggar.',
    image: 'https://images.unsplash.com/photo-1584553421349-3557471bed79?auto=format&fit=crop&q=80&w=600',
    featured: true,
  },
  {
    id: 'brass-diya',
    name: 'Brass Diya Set',
    category: 'Crafts',
    price: 750,
    weight: null,
    description: 'Set of 3 hand-beaten brass diyas (oil lamps) in traditional Pahari style. Perfect for festive seasons.',
    image: 'https://images.unsplash.com/photo-1635153651202-44ec3cfde5a5?auto=format&fit=crop&q=80&w=600',
    featured: false,
  },

  // Wellness
  {
    id: 'deodar-oil',
    name: 'Deodar Wood Oil',
    category: 'Wellness',
    price: 520,
    weight: '30ml',
    description: 'Cold-pressed essential oil from deodar cedar bark. Grounding, woody, and deeply calming aroma.',
    image: 'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?auto=format&fit=crop&q=80&w=600',
    featured: false,
  },
  {
    id: 'pine-soap',
    name: 'Pine Resin Soap',
    category: 'Wellness',
    price: 280,
    weight: '100g',
    description: 'Handmade cold-process soap with Himalayan pine resin, walnut oil, and deodar bark. Naturally antiseptic.',
    image: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&q=80&w=600',
    featured: true,
  },
  {
    id: 'herb-tea',
    name: 'Mountain Herb Tea',
    category: 'Wellness',
    price: 360,
    weight: '50g',
    description: 'A blend of Himalayan herbs: tulsi, rhododendron, and wild mint. Hand-picked from altitudes above 2,500m.',
    image: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&q=80&w=600',
    featured: false,
  },
];

export const categories = ['All', 'Pantry', 'Textiles', 'Crafts', 'Wellness'];

export const featuredProducts = products.filter((p) => p.featured).slice(0, 4);
