export const rooms = [
  {
    id: 'deodar-suite',
    name: 'The Deodar Suite',
    pricePerNight: 4500,
    maxGuests: 2,
    description: 'A spacious wooden haven overlooking cedar forests with a private balcony and soaking tub.',
    features: ['Private balcony', 'Valley view', 'Soaking tub', 'King bed'],
    image: 'https://images.unsplash.com/photo-1519974719765-e6559eac2575?auto=format&fit=crop&q=80&w=600',
  },
  {
    id: 'valley-view',
    name: 'The Valley View',
    pricePerNight: 5500,
    maxGuests: 3,
    description: 'Panoramic windows framing the entire Kullu Valley. Wake up to the Himalayan golden hour.',
    features: ['Floor-to-ceiling windows', 'Fireplace', 'Telescope', 'Queen bed'],
    image: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&q=80&w=600',
  },
  {
    id: 'fireplace-room',
    name: 'The Fireplace Room',
    pricePerNight: 3500,
    maxGuests: 2,
    description: 'Cozy and romantic with a traditional stone fireplace and rich woolen textiles.',
    features: ['Stone fireplace', 'Garden view', 'Woolen decor', 'Double bed'],
    image: 'https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&q=80&w=600',
  },
  {
    id: 'attic-nest',
    name: 'The Attic Nest',
    pricePerNight: 6500,
    maxGuests: 4,
    description: 'A magical space under sloped wooden eaves with skylights for stargazing.',
    features: ['Skylight windows', 'Stargazing deck', 'Sloped ceilings', 'Bunk + Queen'],
    image: 'https://images.unsplash.com/photo-1616486029423-aaa4789e8c9a?auto=format&fit=crop&q=80&w=600',
  },
];
